// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $AnadirComentarios from "./routes/AnadirComentarios.tsx";
import * as $DeleteCommentsRuta from "./routes/DeleteCommentsRuta.tsx";
import * as $FiltrarNombreRuta from "./routes/FiltrarNombreRuta.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $add from "./routes/add.tsx";
import * as $deleteUsuarioRuta from "./routes/deleteUsuarioRuta.tsx";
import * as $index from "./routes/index.tsx";
import * as $loginRuta from "./routes/loginRuta.tsx";
import * as $login_name_ from "./routes/login/[name].tsx";
import * as $paginaUnica_name_ from "./routes/paginaUnica/[name].tsx";
import * as $searchHobbies from "./routes/searchHobbies.tsx";
import * as $searchNombre from "./routes/searchNombre.tsx";
import * as $DeleteComments from "./islands/DeleteComments.tsx";
import * as $DeleteUser from "./islands/DeleteUser.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $PostComments from "./islands/PostComments.tsx";
import * as $SearchName from "./islands/SearchName.tsx";
import * as $SignUp from "./islands/SignUp.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/AnadirComentarios.tsx": $AnadirComentarios,
    "./routes/DeleteCommentsRuta.tsx": $DeleteCommentsRuta,
    "./routes/FiltrarNombreRuta.tsx": $FiltrarNombreRuta,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/add.tsx": $add,
    "./routes/deleteUsuarioRuta.tsx": $deleteUsuarioRuta,
    "./routes/index.tsx": $index,
    "./routes/loginRuta.tsx": $loginRuta,
    "./routes/login/[name].tsx": $login_name_,
    "./routes/paginaUnica/[name].tsx": $paginaUnica_name_,
    "./routes/searchHobbies.tsx": $searchHobbies,
    "./routes/searchNombre.tsx": $searchNombre,
  },
  islands: {
    "./islands/DeleteComments.tsx": $DeleteComments,
    "./islands/DeleteUser.tsx": $DeleteUser,
    "./islands/Login.tsx": $Login,
    "./islands/PostComments.tsx": $PostComments,
    "./islands/SearchName.tsx": $SearchName,
    "./islands/SignUp.tsx": $SignUp,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
